#!/bin/bash

IN=$1
OUT=$2

set -e

echo "3s - static site (with) sed"
echo Parse: $IN/.3s
cmd=""
for key in $(cat $IN/.3s | cut -d":" -f1)
do
    value=$(cat $IN/.3s | grep "^$key" | cut -d":" -f2)
    cmd=$cmd"s/{{$key}}/$value/;"
done
for file in $(find $IN -type f -not -path '*/\.*')
do
    echo Copy: $(sed "s#$IN#$OUT#" <<< $file)
    mkdir -vp $(sed "s#$IN#$OUT#;s#/[^/]*.\$##g" <<< $file)
    cp $file $(sed "s#$IN#$OUT#" <<< $file)
done
for file in $(find $IN -name "*.html")
do
    outfile=$(sed "s#$IN#$OUT#" <<< $file)
    echo Generate: $outfile
    sed -i "$cmd" $outfile
done
